# ----------- CONFIGURABLE START -----------
title:            "MengFly Blog Home"
email:            "www.wangpengfei99@gmail.com"
description:      "感悟、代码、笔记 && 漫画、代码DAIYISIKI"
url:              "https://mengfly.github.io" # 域名
signoff:          "WangPengFei" # Your name
share:            true 

# 分页
paginate: 9
paginate_path: "/page:num.html"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         书籍
    url:          /classify/book.html
    external:     false
  - name:         小说
    url:          /classify/story.html
    external:     false
  - name:         学习笔记
    url:          /classify/learning.html
  - name:         学习资料
    url:          /classify/material.html
    external:     false
  - name:         归档
    url:          /classify/archives.html
    external:     false
  - name:         标签
    url:          /classify/tags.html
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
